### ISSUE TITLE
POSIX Support

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/slug#1]
Implement against by-the-spec POSIX.

**Comment by ghost** [comment]
asyncio for this? or any non-threaded solution

**Comment by AstraLuma** [comment]
AFAIK, the problem is subprocess's specific use of threads in its piping constructs. Using direct pipes we ourselves manage--and avoiding `.communicate()` and friends--should clear this up. If not, we can always abandon subprocess as the underlying process primitive or modifying the Pipe primitives to handle it better.

I am wary of mixing asyncio with threaded code. In my experience, asyncio is infectious, going between threaded and async produces non-trivial code, and I would have to research what level of async the kernels even provide.

Given that every other shell manages to accomplish this task with hardly any threading--never mind async--I think we should start with the simplest possible and then add complexity as needed. At least under Linux, the kernel already does a lot of work with sessions, process groups, etc. We just have to harness these tools.

**Comment by scopatz** [comment]
I agree that asyncio code is infectious. I am in favor of potentially moving the code base in this direction after we drop v3.4, though. Async is much more annoying without `async` and `await`. Still, it isn't an MVP given what code we have now.

**Comment by AstraLuma** [comment]
Closing this because I'm implementing all platforms as I move feature-by-feature. I'll open specific issues if there's platform support holes.
