### ISSUE TITLE
[RFC] Dependency Injection?

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/slug#20]
We have a _lot_ of singletons. Most of them get lumped on to `builtins`, which is ugly and hackish and they have to all be initialized carefully and at once.

Dependency injection would allow us to delay some initialization, clean up namespaces, and make sure that concerns are where they belong.

**Comment by ghost** [comment]
shouldn't this issue be in `xonsh/xonsh` ?

**Comment by AstraLuma** [comment]
*facepalm*
